# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Dependabot auto-merge

on:
  pull_request:

jobs:
  dependabot:
    uses: eclipse-lmos/.github/.github/workflows/dependabot-automerge.yml@main
    permissions:
      contents: write
      pull-requests: write
